// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCesWHk3z6gJvgMhx9NXKUj2Gh-ktaVP9g',
    appId: '1:358035427880:web:33d43be493d376f8de5b1d',
    messagingSenderId: '358035427880',
    projectId: 'e-commerce-7b7a3',
    authDomain: 'e-commerce-7b7a3.firebaseapp.com',
    storageBucket: 'e-commerce-7b7a3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNGoy-XK_6LXL-UcsrwhiIh-bbPvpAip4',
    appId: '1:358035427880:android:47d8de55dbca3ac9de5b1d',
    messagingSenderId: '358035427880',
    projectId: 'e-commerce-7b7a3',
    storageBucket: 'e-commerce-7b7a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3vinY-f1lNglOlSKfxLBamAZN3_hp1Nk',
    appId: '1:358035427880:ios:a81daf8378fa83e5de5b1d',
    messagingSenderId: '358035427880',
    projectId: 'e-commerce-7b7a3',
    storageBucket: 'e-commerce-7b7a3.firebasestorage.app',
    iosBundleId: 'com.example.myProject',
  );
}
